### ISSUE TITLE
ESDoc Hosting Service

### ISSUE THREAD

**Issue by h13i32maru** [Falconerd/flask#1]
Hi!
I am ESDoc developer and thanks for using ESDoc :smile: 

I released [ESDoc Hosting Service](https://doc.esdoc.org) :rocket: 
Register your repository Git URL, this service automatically generate documentation.
If you are interested, please try to use it.
Thanks

**Comment by Falconerd** [comment]
Hi!

Thanks for making an awesome tool. I will be sure to check it out!

Thanks
